import { useCallback, useMemo, useState } from "react";
import { Link, Navigate, useLocation, useNavigate, useSearchParams } from "react-router-dom";
import { IconDownload, IconEditFile, IconShare } from "../components/DocumentPreviewDocToolIcons";
import { WorkspaceHeader } from "../components/WorkspaceHeader";
import { getCreateDocCategoryTitle, isCreateDocCategoryId } from "../data/createDocumentCategories";
import { downloadTextAsPdf } from "../lib/downloadDraftPdf";

function humanizeFileName(file: string): string {
  return file.replace(/\.pdf$/i, "").replace(/_/g, " ");
}

/** Wizard-of-Oz sample copy — not generated by a model. */
function sampleLetterBody(templateLabel: string, brief: string | undefined): string[] {
  const intro =
    brief && brief.trim().length > 0
      ? `The draft below is a preview based on your brief. In a live product, Workbench would refine wording, check policy, and align dates with your HR calendar.`
      : `The draft below is a fixed sample for this proof of concept. Add a brief on the previous step to see how your notes would appear in context.`;

  return [
    intro,
    "",
    `Dear Candidate,`,
    "",
    `We are pleased to extend an offer for the role covered by “${templateLabel}.” This letter summarizes compensation, schedule expectations, and reporting structure for your summer program.`,
    "",
    `Position title: Culinary Intern (Summer Program). Anticipated start: Monday, June 9, 2026, subject to successful completion of onboarding and work authorization verification. Your primary work location will be our flagship kitchen; occasional events off-site may be required with advance notice.`,
    "",
    `Compensation will be $22.00 per hour, paid biweekly in accordance with company payroll. You will be eligible for meal allowances during scheduled shifts as described in the employee handbook.`,
    "",
    `This offer is contingent upon satisfactory reference checks and your agreement to the confidentiality and intellectual property terms attached to this packet.`,
    "",
    `Please sign and return this letter by June 2, 2026 to confirm your acceptance. We are excited about the energy and perspective you would bring to the team.`,
    "",
    `Sincerely,`,
    `People Operations — eatunique`,
  ];
}

export function CreateDocumentAiPreviewPage() {
  const [params] = useSearchParams();
  const { state } = useLocation() as { state?: { brief?: string; documentBody?: string } };
  const navigate = useNavigate();
  const [shareHint, setShareHint] = useState<string | null>(null);
  const file = params.get("file") ?? "";
  const category = params.get("category") ?? "";
  const brief = typeof state?.brief === "string" ? state.brief : undefined;
  const documentBody = typeof state?.documentBody === "string" ? state.documentBody : undefined;

  const valid = file.length > 0 && isCreateDocCategoryId(category);

  const categoryTitle = useMemo(
    () => (isCreateDocCategoryId(category) ? getCreateDocCategoryTitle(category) : ""),
    [category],
  );
  const templateLabel = useMemo(() => humanizeFileName(file), [file]);
  const paragraphs = useMemo(() => {
    if (documentBody != null && documentBody.trim().length > 0) {
      return documentBody.split("\n");
    }
    return sampleLetterBody(templateLabel, brief);
  }, [documentBody, templateLabel, brief]);

  const methodHref = useMemo(
    () => `/create-document/method?${new URLSearchParams({ file, category }).toString()}`,
    [file, category],
  );

  const draftAiHref = useMemo(
    () => `/create-document/draft?${new URLSearchParams({ file, category, method: "ai" }).toString()}`,
    [file, category],
  );

  const documentEditHref = useMemo(
    () => `/create-document/document-edit?${new URLSearchParams({ file, category, source: "ai" }).toString()}`,
    [file, category],
  );

  const plainTextDraft = useMemo(() => paragraphs.join("\n"), [paragraphs]);

  const editFileNavState = useMemo(
    () => ({ brief: brief ?? "", documentBody: plainTextDraft }),
    [brief, plainTextDraft],
  );

  const addToLibrary = useCallback(() => {
    navigate("/documents", {
      state: {
        createMethod: "ai",
        templateFile: file,
        templateCategory: category,
        draftNote: brief?.trim() || undefined,
        aiPreviewAcknowledged: true,
        justAddedToLibrary: true,
      },
    });
  }, [navigate, file, category, brief]);

  const downloadDraftFile = useCallback(() => {
    void downloadTextAsPdf({
      file,
      templateLabel,
      titleLine: templateLabel,
      body: plainTextDraft,
    });
  }, [plainTextDraft, file, templateLabel]);

  const shareDraft = useCallback(async () => {
    const url = typeof window !== "undefined" ? window.location.href : "";
    const title = `${templateLabel} — draft preview`;
    let message = "Link copied.";
    try {
      if (navigator.share) {
        await navigator.share({ title, text: "Draft preview (sample)", url });
        message = "Shared.";
      } else if (navigator.clipboard?.writeText) {
        await navigator.clipboard.writeText(url);
      } else {
        return;
      }
    } catch (e) {
      if ((e as Error)?.name === "AbortError") return;
      try {
        if (navigator.clipboard?.writeText) await navigator.clipboard.writeText(url);
        else return;
      } catch {
        return;
      }
    }
    setShareHint(message);
    window.setTimeout(() => setShareHint(null), 2200);
  }, [templateLabel]);

  if (!valid) {
    return <Navigate to="/create-document/template" replace />;
  }

  const crumbs = (
    <nav className="wb-create-doc__crumbs" aria-label="Breadcrumb">
      <Link to="/create-document/template" className="wb-create-doc__crumb-link">
        Create Document
      </Link>
      <span className="wb-create-doc__crumb-sep" aria-hidden>
        {" "}
        &gt;{" "}
      </span>
      <Link to="/create-document/template" className="wb-create-doc__crumb-link">
        Select template
      </Link>
      <span className="wb-create-doc__crumb-sep" aria-hidden>
        {" "}
        &gt;{" "}
      </span>
      <Link to={`/create-document/templates/${category}`} className="wb-create-doc__crumb-link">
        {categoryTitle}
      </Link>
      <span className="wb-create-doc__crumb-sep" aria-hidden>
        {" "}
        &gt;{" "}
      </span>
      <Link to={methodHref} className="wb-create-doc__crumb-link">
        How to create
      </Link>
      <span className="wb-create-doc__crumb-sep" aria-hidden>
        {" "}
        &gt;{" "}
      </span>
      <Link to={draftAiHref} className="wb-create-doc__crumb-link">
        Describe for AI
      </Link>
      <span className="wb-create-doc__crumb-sep" aria-hidden>
        {" "}
        &gt;{" "}
      </span>
      <span className="wb-create-doc__crumb-current">AI preview</span>
    </nav>
  );

  return (
    <>
      <WorkspaceHeader lead={crumbs} />

      <div className="wb-create-draft-page wb-create-draft-page--ai-preview">
        <header className="wb-create-draft__intro">
          <span className="wb-create-draft__intro-accent" aria-hidden />
          <div className="wb-create-draft__intro-body">
            <p className="wb-create-draft__eyebrow">Wizard-of-Oz preview</p>
            <h1 className="wb-create-draft__title">Here&apos;s your AI draft</h1>
            <p className="wb-create-draft__lede">
              {documentBody != null && documentBody.trim().length > 0 ? (
                <>
                  You&apos;re viewing <strong>your edited letter</strong>. Download or share this version, or use
                  Edit brief to change the starting prompt and regenerate a fresh sample.
                </>
              ) : (
                <>
                  This page shows <strong>sample output</strong> only — no model ran. Use it to review layout
                  and tone before sending anything real.
                </>
              )}
            </p>
          </div>
        </header>

        {brief && brief.trim() ? (
          <aside className="wb-ai-preview__brief" aria-label="Your brief">
            <p className="wb-ai-preview__brief-label">Your brief</p>
            <p className="wb-ai-preview__brief-text">{brief.trim()}</p>
          </aside>
        ) : null}

        <div className="wb-ai-preview__doc-wrap">
          <article className="wb-ai-preview__doc" aria-labelledby="ai-preview-doc-title">
            <div className="wb-ai-preview__doc-head">
              <h2 className="wb-ai-preview__doc-title" id="ai-preview-doc-title">
                {templateLabel}
              </h2>
              <p className="wb-ai-preview__doc-meta">
                PDF preview · {categoryTitle}
                {file.toLowerCase().endsWith(".pdf") ? ` · ${file}` : null}
              </p>
            </div>
            <div className="wb-ai-preview__body">
              {paragraphs.map((line, i) =>
                line === "" ? (
                  <div key={i} className="wb-ai-preview__spacer" aria-hidden />
                ) : (
                  <p key={i} className="wb-ai-preview__para">
                    {line}
                  </p>
                ),
              )}
            </div>
          </article>

          <aside className="wb-ai-preview__doc-tools" aria-label="Document actions">
            <p className="wb-ai-preview__tools-label">Before adding to library</p>
            <button type="button" className="wb-ai-preview__tool" onClick={downloadDraftFile}>
              <IconDownload />
              <span className="wb-ai-preview__tool-text">Download file</span>
            </button>
            <Link to={documentEditHref} className="wb-ai-preview__tool" state={editFileNavState}>
              <IconEditFile />
              <span className="wb-ai-preview__tool-text">Edit file</span>
            </Link>
            <button type="button" className="wb-ai-preview__tool" onClick={shareDraft}>
              <IconShare />
              <span className="wb-ai-preview__tool-text">Share file</span>
            </button>
            {shareHint ? (
              <p className="wb-ai-preview__tools-hint" role="status" aria-live="polite">
                {shareHint}
              </p>
            ) : null}
          </aside>
        </div>

        <div className="wb-create-draft__actions wb-ai-preview__actions">
          <Link to={draftAiHref} className="wb-btn wb-btn--muted wb-create-draft__back">
            ← Edit brief
          </Link>
          <button type="button" className="wb-btn wb-btn--primary" onClick={addToLibrary}>
            Add to library
          </button>
        </div>
      </div>
    </>
  );
}
